export const types = {
  savePokemonTypes: "[home] savePokemonTypes",
  selectType: "[home] selectType",
  savePokemon: "[home] savePokemon",
  setCurrentPokemonList: "[home] setCurrentPokemonList",
  setFetchError: "[home] setFetchError",
  updatePokemonList: "[home] updatePokemonList",
  updateHomeStatus: "[home] updateHomeStatus",
  setPokemonDetails: "[details] setPokemonDetails",
  savePokemonListDetails: "[details] savePokemonList",
  setArenaPokemon: "[arena] setCurrentPokemon",
  enableArena: "[arena] enabled",
  disableArena: "[arena] disabled",
  throwPokeball: "[arena] throwPokeball",
  pokeballSuccess: "[arena] pokeballSuccess",
  savePokemonInPC: "[pc] savePokemon",
};
